# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8238ac50eb4d44042610261adda65221e820d63105744997f80a7e6e43f09b5c5c12200664a5dd6dd98aa1300292f902e26aac22e24b4df7c89d989fd3abaa4d

test:
  secret_key_base: d0ca98861b1ebfa5c3f6d7cc01412d494790b4eda22fa6d2dcf567410494169b644a26736ad35dbaa59e3e69a91dd818f07443d585fff3ca398838d6ec851af2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
